revisor_conferencias:
  - conferencia: "IEEE/ACM International Conference on Program Comprehension"
    acronimo: "ICPC"
    core: "A"
    roles:
      - "PC Member - Main Research Track: 2025, 2026"
    estado: "Actualmente"  
  
  - conferencia: "IEEE International Conference on Software Maintenance and Evolution"
    acronimo: "ICSME"
    core: "A"
    roles:
      - "PC Member - Visions and Emerging Results Track : 2026"
      - "PC Member - Tool Demonstration and Data Showcase Track : 2025, 2026"
    estado: "Actualmente" 
    
  - conferencia: "International Conference on Mining Software Repositories"
    acronimo: "MSR"
    core: "A"
    roles:
      - "PC Member - Main Research Track (Junior PC): 2026"
      - "PC Member - Data and Tool Showcase Track: 2025"
    estado: "Actualmente"

  - conferencia: "IEEE International Conference on Software Analysis, Evolution and Reengineering"
    acronimo: "SANER"
    core: "A"
    roles:
      - "PC Member - Early Research Achievement (ERA): 2023, 2024, 2025"
    estado: "Actualmente"

  - conferencia: "IEEE Working Conference on Software Visualization"
    acronimo: "IEEE VISSOFT"
    core: "B"
    roles:
      - "PC Member - Main Research Track: 2018, 2019, 2020, 2022, 2023, 2024, 2025"
      - "PC Chair - Main Research Track: 2021"
    estado: "Actualmente"

  - conferencia: "Conference on Human Factors in Computing Systems"
    acronimo: "CHI"
    core: "A*"
    roles:
      - "External Reviewer: 2025"

  - conferencia: "Conference on Visualization"
    acronimo: "PACIFIC-VIS"
    core: "B"
    roles:
      - "External Reviewer: 2017"

  - conferencia: "EG/VGTC Conference on Visualization"
    acronimo: "EUROVIS"
    core: "B"
    roles:
      - "External Reviewer: 2017"

revisor_revistas:
  - acronimo: "EMSE"
    revista: "Empirical Software Engineering (Q1)"
    rol: "Reviewer"
  - acronimo: "JSS"
    revista: "Journal Software and Systems (Q1)"
    rol: "Reviewer"
  - acronimo: "IST"
    revista: "Information and Software Technology (Q1)"
    rol: "Guest Editor special issue on Software Visualization"
    year: "2021"